### ISSUE TITLE
Request to give installaion walk-through 

### ISSUE THREAD

**Issue by mdzakirhussain** [Cloud-V/Fault#5] opened 2019-11-25 10:57 UTC
Dear,

I humbly request you to give step-by-step clean walk-through tutorial as to how to install. There is lot of confusion in the current shown approach. 

Please, it is a request.

**Comment by donn** [comment] 2019-11-25 11:20
Sure. Watch #4, I think we will be working on a simple tutorial there. :)

**Comment by donn** [comment] 2019-11-25 12:45
(Duplicate of #4, closed.)

**Closed by donn** 2019-11-25 12:45 UTC
Labels: documentation, help wanted
